services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - db_pg:/var/lib/postgresql/data
    networks:
      - dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: redis
    volumes:
      - redisdata:/data
    networks:
      - dbnet
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    image: printer-shop_image
    container_name: printer-shop
    ports:
      - "8000:8000"
    networks: 
      - dbnet
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
networks:
  dbnet:
    driver: bridge

volumes:
  db_pg:
  redisdata: