services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: redis:8.0
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - db_pg:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  db_pg:
  redisdata: